version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Budget
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Budget-App
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Budget-App
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
